[package]
name = "triangular_arbitrage"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = "0.7"

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Concurrency utilities
futures = "0.3"

# HTTP middleware (CORS + static file serving)
tower-http = { version = "0.5", features = ["cors", "fs"] }
