[package]
name = "triangular_arbitrage"
version = "0.1.0"
edition = "2021"

[dependencies]
# async runtime
tokio = { version = "1.40", features = ["full"] }

# web framework
axum = "0.7"

# HTTP client for exchange APIs
reqwest = { version = "0.11", features = ["json", "gzip"] }

# serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CORS & static file serving
tower-http = { version = "0.5", features = ["cors", "fs"] }

# logging (optional, useful for debugging)
tracing = "0.1"
tracing-subscriber = "0.3"
