[package]
name = "triangular_arbitrage"
version = "0.1.0"
edition = "2021"

[dependencies]
# HTTP client for REST API calls
reqwest = { version = "0.11", features = ["json"] }

# Async runtime for handling concurrent tasks
tokio = { version = "1.37", features = ["full"] }

# Serialization and deserialization for JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Futures and async utilities
futures = "0.3"
