[package]
name = "triangular_arbitrage"
version = "0.1.0"
edition = "2021"

[dependencies]
# HTTP and async
reqwest = { version = "0.11.23", features = ["json"] }
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
futures = "0.3.30"

# GUI
eframe = "0.24.0"
egui = "0.24.0"
